### ISSUE TITLE
按照步骤集成之后，报错 Undefined symbol: _Py_DecodeLocale

### ISSUE THREAD

**Issue by chenguangdong** [cocoonbud/THPythonExecutor#1]
ld: warning: ignoring file /Users/zkkx/Desktop/KangxinApp/KangxinApp/Lib/Python-3.8-iOS-support.b7/Python/libPython.a, building for iOS Simulator-x86_64 but attempting to link with file built for unknown-unsupported file format ( 0x76 0x65 0x72 0x73 0x69 0x6F 0x6E 0x20 0x68 0x74 0x74 0x70 0x73 0x3A 0x2F 0x2F )
Undefined symbols for architecture x86_64:
  "_Py_DecodeLocale", referenced from:
      -[THPythonExecutor p_setHomePath] in THPythonExecutor.o
  "_PyImport_ImportModule", referenced from:
      -[THPythonExecutor p_importModuleWithClassName:] in THPythonExecutor.o
  "_PyObject_GetAttrString", referenced from:
      -[THPythonExecutor p_importModuleWithClassName:] in THPythonExecutor.o
  "_PyArg_Parse", referenced from:
      -[THPythonExecutor p_performMethod:paramterJsonString:] in THPythonExecutor.o
  "_PyInstanceMethod_New", referenced from:
      -[THPythonExecutor p_importModuleWithClassName:] in THPythonExecutor.o
  "_PyObject_CallMethod", referenced from:
      -[THPythonExecutor p_performMethod:paramterJsonString:] in THPythonExecutor.o
  "__Py_Dealloc", referenced from:
      __Py_DECREF in THPythonExecutor.o
  "_Py_Initialize", referenced from:
      -[THPythonExecutor initWithModuleName:] in THPythonExecutor.o
  "_Py_SetPythonHome", referenced from:
      -[THPythonExecutor p_setHomePath] in THPythonExecutor.o
  "_Py_Finalize", referenced from:
      -[THPythonExecutor dealloc] in THPythonExecutor.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Undefined symbol: _Py_DecodeLocale
Undefined symbol: _PyImport_ImportModule
Undefined symbol: _PyArg_Parse
Undefined symbol: _PyInstanceMethod_New
Undefined symbol: _PyObject_CallMethod
Undefined symbol: __Py_Dealloc
Undefined symbol: _Py_Initialize
Undefined symbol: _Py_SetPythonHome
Undefined symbol: _Py_Finalize

已经添加了依赖库 libsqlite3.tbd、libz.tbd，依然报错，请问什么原因

**Comment by cocoonbud** [comment]
你跑我原版demo可以run起来么。注意原本demo中Lib group下内容。
